#!/usr/bin/env bash

wallpaper=$(find ~/Pictures/Wallpapers/ -type f | shuf --random-source=/dev/urandom -n 1)

echo $wallpaper

echo -ne "preload = $wallpaper \n \n wallpaper = HDMI-A-1,$wallpaper" > ~/.config/hypr/hyprpaper.conf

hyprpaper
